kernel:
  image: linuxkit/kernel:4.14.40
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:v0.4
  - linuxkit/runc:v0.4
  - linuxkit/containerd:v0.4
  - linuxkit/ca-certificates:v0.4
  - cattlek8s/cni-plugins:4256039b190ad997c57c612d0a5c6ab75332224b
  - cattlek8s/critools:d8e07ef0b2c91a096267fac5db6905aa48f2eef5
  - cattlek8s/kubelet:15bface98626a8ccf08d5bf0128b2866d29c2317
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.4
    binds:
     - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
    readonly: false
  - name: sysfs
    image: linuxkit/sysfs:v0.4
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.4
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.4
  - name: format
    image: linuxkit/format:v0.4
  - name: mounts
    image: linuxkit/mount:v0.4
    command: ["/usr/bin/mountie", "/var/lib/"]
services:
  - name: getty
    image: linuxkit/getty:v0.4
    env:
     - INSECURE=true
    cgroupsPath: systemreserved/getty
  - name: rngd
    image: linuxkit/rngd:v0.4
    cgroupsPath: systemreserved/rngd
  - name: ntpd
    image: linuxkit/openntpd:v0.4
    cgroupsPath: systemreserved/ntpd
  - name: sshd
    image: linuxkit/sshd:v0.4
    cgroupsPath: systemreserved/sshd
files:
  - path: /etc/kubernetes
    directory: true
  - path: /etc/crictl.yaml
    contents: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 10
  - path: /etc/sysctl.d/01-kubernetes.conf
    contents: 'net.ipv4.ip_forward = 1'
  - path: /etc/cni/net.d
    directory: true
  - path: /opt/cni/bin
    directory: true
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: /etc/containerd/config.toml
    contents: |
      state = "/run/containerd"
      root = "/var/lib/containerd"
      snapshotter = "io.containerd.snapshotter.v1.overlayfs"
      
      [grpc]
        address = "/run/containerd/containerd.sock"
        uid = 0
        gid = 0
      
      [debug]
        address = "/run/containerd/debug.sock"
        level = "info"
      
      [metrics]
        address = ""
trust:
  org:
    - linuxkit
    - library
